stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - data/heart_df.parquet
      - src/preprocessing.py
    params:
      - preprocessing.test_size
      - preprocessing.random_state
    outs:
      - data/processed_train.parquet
      - data/processed_test.parquet