stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/adult.data
      - src/preprocessing.py
    params:
      - preprocessing.test_size
      - preprocessing.random_state
      - preprocessing.input_path
      - preprocessing.train_output_path
      - preprocessing.test_output_path
    outs:
      - data/processed_train.csv
      - data/processed_test.csv
